### ISSUE TITLE
TypeError: exec_module() missing 1 required positional argument: 'module'

### ISSUE THREAD

**Issue by CV-ShuchangLyu** [Fonbet/argus-tensor-stream#11]
I have ran ''python setup.py install'', but go wrong while running python simple.py.
Thanks, please respones

Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensor_stream
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/lsc/anaconda3/lib/python3.6/site-packages/tensor_stream-0.4.0-py3.6-linux-x86_64.egg/tensor_stream/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/lsc/anaconda3/lib/python3.6/site-packages/tensor_stream-0.4.0-py3.6-linux-x86_64.egg/tensor_stream/tensor_stream.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/lsc/anaconda3/lib/python3.6/site-packages/tensor_stream-0.4.0-py3.6-linux-x86_64.egg/TensorStream.py", line 8, in <module>
  File "/home/lsc/anaconda3/lib/python3.6/site-packages/tensor_stream-0.4.0-py3.6-linux-x86_64.egg/TensorStream.py", line 7, in __bootstrap__
TypeError: exec_module() missing 1 required positional argument: 'module'

**Comment by BykadorovR** [comment]
Hi @bh1slsc199312 
Could you please reinstall TensorStream and share the log from installation? You can delete dist, build, tensor_stream.egg-info folders and execute python setup.py install.

**Comment by CV-ShuchangLyu** [comment]
hi thanks for responding! I followed your tips and attach the installation log,
Unfortunately, still went wrong while executing simple.py  
[install.txt](https://github.com/osai-ai/tensor-stream/files/4875193/install.txt)

**Comment by BykadorovR** [comment]
I don't see code compilation steps in your log, looks like you haven't deleted build folder or build artifacts have been found in another place on your PC, so please try to re-clone repo, execute "python setup.py install" again and attach log.
The issue you faced is related to some installation issues, so TensorStream extension hasn't been built correctly and you can't export it.
BTW, if you want just use TensorStream, you can install it via pip: https://github.com/osai-ai/tensor-stream#binaries-linux-only

**Comment by CV-ShuchangLyu** [comment]
Feeling confused about the result
I did as you told me. The install info is printed in install.log
The problem still exists, sorry for bothering for naive question! 

git clone -b master --single-branch https://github.com/Fonbet/argus-tensor-stream.git
cd argus-tensor-stream
python setup.py install

[install.log](https://github.com/osai-ai/tensor-stream/files/4875351/install.log)

**Comment by BykadorovR** [comment]
Now I see compilation steps, but don't see any errors (sometimes you can build extension even with errors during compilation if execute setup.py install several times in row) so looks like the issue is related somehow to your environment (maybe the issue is observed due to Anaconda, please check that the same Python version is used for build and execution).

**Comment by CV-ShuchangLyu** [comment]
That's confusing. I mean tensorstream can work well in c_example. But still no working on python extension

**Comment by BykadorovR** [comment]
I still believe that it's some environment issue so some dependencies for TensorStream execution can't be found. I can suggest you to re-install Python (just use pure Python without Anaconda) and see if it helps.
BTW, you can use Docker with this [Dockerfile](https://github.com/osai-ai/tensor-stream/blob/master/Dockerfile) to do pure TensorStream installation on tested environment.

**Comment by BykadorovR** [comment]
Hi @bh1slsc199312, 
Have you successfully installed TensorStream or still have issues with installation?

**Comment by CV-ShuchangLyu** [comment]
sorry I still have this issue. And I choose to use c++ version

**Comment by BykadorovR** [comment]
I think it can be issue with setuptools, can you try to reinstall it? (It's pip module)
Btw, have you tried Docker/re-install Python or now you're ok with C++ version?
