### ISSUE TITLE
python example import error

### ISSUE THREAD

**Issue by andreasHan** [Fonbet/argus-tensor-stream#21]
Run simple.py example Import error

Traceback (most recent call last):
  File "simple.py", line 1, in <module>
    from tensor_stream import TensorStreamConverter
  File "/home/edge/miniconda3/lib/python3.7/site-packages/tensor_stream-0.4.0-py3.7-linux-x86_64.egg/tensor_stream/__init__.py", line 1, in <module>
  File "/home/edge/miniconda3/lib/python3.7/site-packages/tensor_stream-0.4.0-py3.7-linux-x86_64.egg/tensor_stream/tensor_stream.py", line 2, in <module>
  File "/home/edge/miniconda3/lib/python3.7/site-packages/tensor_stream-0.4.0-py3.7-linux-x86_64.egg/TensorStream.py", line 7, in <module>
  File "/home/edge/miniconda3/lib/python3.7/site-packages/tensor_stream-0.4.0-py3.7-linux-x86_64.egg/TensorStream.py", line 6, in __bootstrap__
  File "/home/edge/miniconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/edge/.cache/Python-Eggs/tensor_stream-0.4.0-py3.7-linux-x86_64.egg-tmp/TensorStream.cpython-37m-x86_64-linux-gnu.so: undefined symbol: ff_interleaved_golomb_vlc_len

Thx!

**Comment by BykadorovR** [comment]
Hi @andreasHan,
Looks like you have issues with FFmpeg installation

**Comment by andreasHan** [comment]
Solved~
follow the ffmpeg installation from dockerfile
